export const PRICING_PLANS = [
  {
    name: "FREE PLAN",
    icon: "/assets/icons/free-plan-icon.svg",
    description: "Perfect for individuals with simple needs.",
    price: "$0",
    priceDescription: "per million requests",
    glowColor: "#CCCCCC",
    borderColor: "#CCCCCC",
    features: [
      "1 API key",
      "20,000 requests/month",
      "5 requests per second",
      "Community support",
    ],
  },
  {
    name: "PRO PLAN",
    icon: "/assets/icons/pro-plan-icon.svg",
    description: "Best for teams & startups",
    price: "$200",
    priceDescription: "per million requests",
    glowColor: "#417EC0",
    borderColor: "#63AAE0",
    features: [
      "5 API keys",
      "1,000,000 requests/month",
      "300 requests/second",
      "Priority support",
      "Websockets",
      "Webhooks",
    ],
    isFeatured: true,
  },
  {
    name: "ENTERPRISE PLAN",
    icon: "/assets/icons/enterprise-plan-icon.svg",
    description: "Tailored solutions for large companies",
    price: "Custom",
    priceDescription: "per million requests",
    glowColor: "#BC7DFF",
    borderColor: "#BC7DFF",
    features: [
      "Unlimited API keys",
      "Unlimited requests/month",
      "Custom requests/second",
      "Dedicated support",
      "Websockets",
      "Webhooks",
      "Custom SLAs",
      "High concurrency",
    ],
    isCustom: true,
  },
];
